CREATE EXTERNAL TABLE `compute_optimizer_auto_scale_lines`(
  `accountid` string COMMENT 'from deserializer', 
  `autoscalinggrouparn` string COMMENT 'from deserializer', 
  `autoscalinggroupname` string COMMENT 'from deserializer', 
  `finding` string COMMENT 'from deserializer', 
  `utilizationmetrics_cpu_maximum` string COMMENT 'from deserializer', 
  `utilizationmetrics_memory_maximum` string COMMENT 'from deserializer', 
  `lookbackperiodindays` string COMMENT 'from deserializer', 
  `currentconfiguration_desiredcapacity` string COMMENT 'from deserializer', 
  `currentconfiguration_minsize` string COMMENT 'from deserializer', 
  `currentconfiguration_maxsize` string COMMENT 'from deserializer', 
  `currentconfiguration_instancetype` string COMMENT 'from deserializer', 
  `current_vcpus` string COMMENT 'from deserializer', 
  `current_memory` string COMMENT 'from deserializer', 
  `current_storage` string COMMENT 'from deserializer', 
  `current_network` string COMMENT 'from deserializer', 
  `current_ondemandprice` string COMMENT 'from deserializer', 
  `current_standardoneyearnoupfrontreservedprice` string COMMENT 'from deserializer', 
  `current_standardthreeyearnoupfrontreservedprice` string COMMENT 'from deserializer', 
  `recommendations_count` string COMMENT 'from deserializer', 
  `recommendationoptions_1_configuration_desiredcapacity` string COMMENT 'from deserializer', 
  `recommendationoptions_2_configuration_desiredcapacity` string COMMENT 'from deserializer', 
  `recommendationoptions_3_configuration_desiredcapacity` string COMMENT 'from deserializer', 
  `recommendationoptions_1_configuration_minsize` string COMMENT 'from deserializer', 
  `recommendationoptions_2_configuration_minsize` string COMMENT 'from deserializer', 
  `recommendationoptions_3_configuration_minsize` string COMMENT 'from deserializer', 
  `recommendationoptions_1_configuration_maxsize` string COMMENT 'from deserializer', 
  `recommendationoptions_2_configuration_maxsize` string COMMENT 'from deserializer', 
  `recommendationoptions_3_configuration_maxsize` string COMMENT 'from deserializer', 
  `recommendationoptions_1_configuration_instancetype` string COMMENT 'from deserializer', 
  `recommendationoptions_2_configuration_instancetype` string COMMENT 'from deserializer', 
  `recommendationoptions_3_configuration_instancetype` string COMMENT 'from deserializer', 
  `recommendationoptions_1_projectedutilizationmetrics_cpu_maximum` string COMMENT 'from deserializer', 
  `recommendationoptions_2_projectedutilizationmetrics_cpu_maximum` string COMMENT 'from deserializer', 
  `recommendationoptions_3_projectedutilizationmetrics_cpu_maximum` string COMMENT 'from deserializer', 
  `recommendationoptions_1_projectedutilizationmetrics_memory_maximum` string COMMENT 'from deserializer', 
  `recommendationoptions_2_projectedutilizationmetrics_memory_maximum` string COMMENT 'from deserializer', 
  `recommendationoptions_3_projectedutilizationmetrics_memory_maximum` string COMMENT 'from deserializer', 
  `recommendationoptions_1_performancerisk` string COMMENT 'from deserializer', 
  `recommendationoptions_2_performancerisk` string COMMENT 'from deserializer', 
  `recommendationoptions_3_performancerisk` string COMMENT 'from deserializer', 
  `recommendationoptions_1_vcpus` string COMMENT 'from deserializer', 
  `recommendationoptions_2_vcpus` string COMMENT 'from deserializer', 
  `recommendationoptions_3_vcpus` string COMMENT 'from deserializer', 
  `recommendationoptions_1_memory` string COMMENT 'from deserializer', 
  `recommendationoptions_2_memory` string COMMENT 'from deserializer', 
  `recommendationoptions_3_memory` string COMMENT 'from deserializer', 
  `recommendationoptions_1_storage` string COMMENT 'from deserializer', 
  `recommendationoptions_2_storage` string COMMENT 'from deserializer', 
  `recommendationoptions_3_storage` string COMMENT 'from deserializer', 
  `recommendationoptions_1_network` string COMMENT 'from deserializer', 
  `recommendationoptions_2_network` string COMMENT 'from deserializer', 
  `recommendationoptions_3_network` string COMMENT 'from deserializer', 
  `recommendationoptions_1_ondemandprice` string COMMENT 'from deserializer', 
  `recommendationoptions_2_ondemandprice` string COMMENT 'from deserializer', 
  `recommendationoptions_3_ondemandprice` string COMMENT 'from deserializer', 
  `recommendationoptions_1_standardoneyearnoupfrontreservedprice` string COMMENT 'from deserializer', 
  `recommendationoptions_2_standardoneyearnoupfrontreservedprice` string COMMENT 'from deserializer', 
  `recommendationoptions_3_standardoneyearnoupfrontreservedprice` string COMMENT 'from deserializer', 
  `recommendationoptions_1_standardthreeyearnoupfrontreservedprice` string COMMENT 'from deserializer', 
  `recommendationoptions_2_standardthreeyearnoupfrontreservedprice` string COMMENT 'from deserializer', 
  `recommendationoptions_3_standardthreeyearnoupfrontreservedprice` string COMMENT 'from deserializer', 
  `lastrefreshtimestamp_utc` string COMMENT 'from deserializer', 
  `errorcode` string COMMENT 'from deserializer', 
  `errormessage` string COMMENT 'from deserializer', 
  `utilizationmetrics_ebs_read_ops_per_second_maximum` string COMMENT 'from deserializer', 
  `utilizationmetrics_ebs_write_ops_per_second_maximum` string COMMENT 'from deserializer', 
  `utilizationmetrics_ebs_read_bytes_per_second_maximum` string COMMENT 'from deserializer', 
  `utilizationmetrics_ebs_write_bytes_per_second_maximum` string COMMENT 'from deserializer', 
  `utilizationmetrics_network_in_bytes_per_second_maximum` string COMMENT 'from deserializer', 
  `utilizationmetrics_network_out_bytes_per_second_maximum` string COMMENT 'from deserializer', 
  `utilizationmetrics_network_packets_in_per_second_maximum` string COMMENT 'from deserializer', 
  `utilizationmetrics_network_packets_out_per_second_maximum` string COMMENT 'from deserializer', 
  `utilizationmetrics_disk_read_ops_per_second_maximum` string COMMENT 'from deserializer', 
  `utilizationmetrics_disk_write_ops_per_second_maximum` string COMMENT 'from deserializer', 
  `utilizationmetrics_disk_read_bytes_per_second_maximum` string COMMENT 'from deserializer', 
  `utilizationmetrics_disk_write_bytes_per_second_maximum` string COMMENT 'from deserializer', 
  `currentperformancerisk` string COMMENT 'from deserializer', 
  `recommendationoptions_1_savingsopportunitypercentage` string COMMENT 'from deserializer', 
  `recommendationoptions_1_estimatedmonthlysavings_currency` string COMMENT 'from deserializer', 
  `recommendationoptions_1_estimatedmonthlysavings_value` string COMMENT 'from deserializer', 
  `recommendationoptions_2_savingsopportunitypercentage` string COMMENT 'from deserializer', 
  `recommendationoptions_2_estimatedmonthlysavings_currency` string COMMENT 'from deserializer', 
  `recommendationoptions_2_estimatedmonthlysavings_value` string COMMENT 'from deserializer', 
  `recommendationoptions_3_savingsopportunitypercentage` string COMMENT 'from deserializer', 
  `recommendationoptions_3_estimatedmonthlysavings_currency` string COMMENT 'from deserializer', 
  `recommendationoptions_3_estimatedmonthlysavings_value` string COMMENT 'from deserializer', 
  `effectiverecommendationpreferencesinferredworkloadtypes` string COMMENT 'from deserializer', 
  `inferredworkloadtypes` string COMMENT 'from deserializer', 
  `recommendationoptions_1_migrationeffort` string COMMENT 'from deserializer', 
  `recommendationoptions_2_migrationeffort` string COMMENT 'from deserializer', 
  `recommendationoptions_3_migrationeffort` string COMMENT 'from deserializer', 
  `effectiverecommendationpreferencescpuvendorarchitectures` string COMMENT 'from deserializer', 
  `effectiverecommendationpreferencesenhancedinfrastructuremetrics` string COMMENT 'from deserializer')
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
WITH SERDEPROPERTIES ( 
  'quoteChar'='\"', 
  'separatorChar'=',') 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  's3://data-bucket/compute_optimizer/compute_optimizer_auto_scale'
TBLPROPERTIES (
  'skip.header.line.count'='1')