CREATE EXTERNAL TABLE `compute_optimizer_ec2_instance_lines`(
  `accountid` string COMMENT 'from deserializer', 
  `instancearn` string COMMENT 'from deserializer', 
  `instancename` string COMMENT 'from deserializer', 
  `currentinstancetype` string COMMENT 'from deserializer', 
  `finding` string COMMENT 'from deserializer', 
  `utilizationmetrics_cpu_maximum` string COMMENT 'from deserializer', 
  `utilizationmetrics_memory_maximum` string COMMENT 'from deserializer', 
  `lookbackperiodindays` string COMMENT 'from deserializer', 
  `current_vcpus` string COMMENT 'from deserializer', 
  `current_memory` string COMMENT 'from deserializer', 
  `current_storage` string COMMENT 'from deserializer', 
  `current_network` string COMMENT 'from deserializer', 
  `current_ondemandprice` string COMMENT 'from deserializer', 
  `current_standardoneyearnoupfrontreservedprice` string COMMENT 'from deserializer', 
  `current_standardthreeyearnoupfrontreservedprice` string COMMENT 'from deserializer', 
  `recommendations_count` string COMMENT 'from deserializer', 
  `recommendationoptions_1_instancetype` string COMMENT 'from deserializer', 
  `recommendationoptions_2_instancetype` string COMMENT 'from deserializer', 
  `recommendationoptions_3_instancetype` string COMMENT 'from deserializer', 
  `recommendationoptions_1_projectedutilizationmetrics_cpu_maximum` string COMMENT 'from deserializer', 
  `recommendationoptions_2_projectedutilizationmetrics_cpu_maximum` string COMMENT 'from deserializer', 
  `recommendationoptions_3_projectedutilizationmetrics_cpu_maximum` string COMMENT 'from deserializer', 
  `recommendationoptions_1_projectedutilizationmetrics_memory_maximum` string COMMENT 'from deserializer', 
  `recommendationoptions_2_projectedutilizationmetrics_memory_maximum` string COMMENT 'from deserializer', 
  `recommendationoptions_3_projectedutilizationmetrics_memory_maximum` string COMMENT 'from deserializer', 
  `recommendationoptions_1_performancerisk` string COMMENT 'from deserializer', 
  `recommendationoptions_2_performancerisk` string COMMENT 'from deserializer', 
  `recommendationoptions_3_performancerisk` string COMMENT 'from deserializer', 
  `recommendationoptions_1_vcpus` string COMMENT 'from deserializer', 
  `recommendationoptions_2_vcpus` string COMMENT 'from deserializer', 
  `recommendationoptions_3_vcpus` string COMMENT 'from deserializer', 
  `recommendationoptions_1_memory` string COMMENT 'from deserializer', 
  `recommendationoptions_2_memory` string COMMENT 'from deserializer', 
  `recommendationoptions_3_memory` string COMMENT 'from deserializer', 
  `recommendationoptions_1_storage` string COMMENT 'from deserializer', 
  `recommendationoptions_2_storage` string COMMENT 'from deserializer', 
  `recommendationoptions_3_storage` string COMMENT 'from deserializer', 
  `recommendationoptions_1_network` string COMMENT 'from deserializer', 
  `recommendationoptions_2_network` string COMMENT 'from deserializer', 
  `recommendationoptions_3_network` string COMMENT 'from deserializer', 
  `recommendationoptions_1_ondemandprice` string COMMENT 'from deserializer', 
  `recommendationoptions_2_ondemandprice` string COMMENT 'from deserializer', 
  `recommendationoptions_3_ondemandprice` string COMMENT 'from deserializer', 
  `recommendationoptions_1_standardoneyearnoupfrontreservedprice` string COMMENT 'from deserializer', 
  `recommendationoptions_2_standardoneyearnoupfrontreservedprice` string COMMENT 'from deserializer', 
  `recommendationoptions_3_standardoneyearnoupfrontreservedprice` string COMMENT 'from deserializer', 
  `recommendationoptions_1_standardthreeyearnoupfrontreservedprice` string COMMENT 'from deserializer', 
  `recommendationoptions_2_standardthreeyearnoupfrontreservedprice` string COMMENT 'from deserializer', 
  `recommendationoptions_3_standardthreeyearnoupfrontreservedprice` string COMMENT 'from deserializer', 
  `recommendationssources_1_recommendationsourcearn` string COMMENT 'from deserializer', 
  `recommendationssources_1_recommendationsourcetype` string COMMENT 'from deserializer', 
  `lastrefreshtimestamp_utc` string COMMENT 'from deserializer', 
  `errorcode` string COMMENT 'from deserializer', 
  `errormessage` string COMMENT 'from deserializer', 
  `utilizationmetrics_ebs_read_ops_per_second_maximum` string COMMENT 'from deserializer', 
  `utilizationmetrics_ebs_write_ops_per_second_maximum` string COMMENT 'from deserializer', 
  `utilizationmetrics_ebs_read_bytes_per_second_maximum` string COMMENT 'from deserializer', 
  `utilizationmetrics_ebs_write_bytes_per_second_maximum` string COMMENT 'from deserializer', 
  `recommendationoptions_1_platformdifferences_ishypervisordifferent` string COMMENT 'from deserializer', 
  `recommendationoptions_1_platformdifferences_isnetworkinterfacedifferent` string COMMENT 'from deserializer', 
  `recommendationoptions_1_platformdifferences_isstorageinterfacedifferent` string COMMENT 'from deserializer', 
  `recommendationoptions_1_platformdifferences_isinstancestoreavailabilitydifferent` string COMMENT 'from deserializer', 
  `recommendationoptions_1_platformdifferences_isvirtualizationtypedifferent` string COMMENT 'from deserializer', 
  `recommendationoptions_2_platformdifferences_ishypervisordifferent` string COMMENT 'from deserializer', 
  `recommendationoptions_2_platformdifferences_isnetworkinterfacedifferent` string COMMENT 'from deserializer', 
  `recommendationoptions_2_platformdifferences_isstorageinterfacedifferent` string COMMENT 'from deserializer', 
  `recommendationoptions_2_platformdifferences_isinstancestoreavailabilitydifferent` string COMMENT 'from deserializer', 
  `recommendationoptions_2_platformdifferences_isvirtualizationtypedifferent` string COMMENT 'from deserializer', 
  `recommendationoptions_3_platformdifferences_ishypervisordifferent` string COMMENT 'from deserializer', 
  `recommendationoptions_3_platformdifferences_isnetworkinterfacedifferent` string COMMENT 'from deserializer', 
  `recommendationoptions_3_platformdifferences_isstorageinterfacedifferent` string COMMENT 'from deserializer', 
  `recommendationoptions_3_platformdifferences_isinstancestoreavailabilitydifferent` string COMMENT 'from deserializer', 
  `recommendationoptions_3_platformdifferences_isvirtualizationtypedifferent` string COMMENT 'from deserializer', 
  `findingreasoncodes_iscpuoverprovisioned` string COMMENT 'from deserializer', 
  `findingreasoncodes_iscpuunderprovisioned` string COMMENT 'from deserializer', 
  `findingreasoncodes_ismemoryoverprovisioned` string COMMENT 'from deserializer', 
  `findingreasoncodes_ismemoryunderprovisioned` string COMMENT 'from deserializer', 
  `findingreasoncodes_isebsthroughputoverprovisioned` string COMMENT 'from deserializer', 
  `findingreasoncodes_isebsthroughputunderprovisioned` string COMMENT 'from deserializer', 
  `findingreasoncodes_isebsiopsoverprovisioned` string COMMENT 'from deserializer', 
  `findingreasoncodes_isebsiopsunderprovisioned` string COMMENT 'from deserializer', 
  `findingreasoncodes_isnetworkbandwidthoverprovisioned` string COMMENT 'from deserializer', 
  `findingreasoncodes_isnetworkbandwidthunderprovisioned` string COMMENT 'from deserializer', 
  `findingreasoncodes_isnetworkppsoverprovisioned` string COMMENT 'from deserializer', 
  `findingreasoncodes_isnetworkppsunderprovisioned` string COMMENT 'from deserializer', 
  `findingreasoncodes_isdiskiopsoverprovisioned` string COMMENT 'from deserializer', 
  `findingreasoncodes_isdiskiopsunderprovisioned` string COMMENT 'from deserializer', 
  `findingreasoncodes_isdiskthroughputoverprovisioned` string COMMENT 'from deserializer', 
  `findingreasoncodes_isdiskthroughputunderprovisioned` string COMMENT 'from deserializer', 
  `utilizationmetrics_network_in_bytes_per_second_maximum` string COMMENT 'from deserializer', 
  `utilizationmetrics_network_out_bytes_per_second_maximum` string COMMENT 'from deserializer', 
  `utilizationmetrics_network_packets_in_per_second_maximum` string COMMENT 'from deserializer', 
  `utilizationmetrics_network_packets_out_per_second_maximum` string COMMENT 'from deserializer', 
  `utilizationmetrics_disk_read_ops_per_second_maximum` string COMMENT 'from deserializer', 
  `utilizationmetrics_disk_write_ops_per_second_maximum` string COMMENT 'from deserializer', 
  `utilizationmetrics_disk_read_bytes_per_second_maximum` string COMMENT 'from deserializer', 
  `utilizationmetrics_disk_write_bytes_per_second_maximum` string COMMENT 'from deserializer', 
  `recommendationoptions_1_platformdifferences_isarchitecturedifferent` string COMMENT 'from deserializer', 
  `recommendationoptions_2_platformdifferences_isarchitecturedifferent` string COMMENT 'from deserializer', 
  `recommendationoptions_3_platformdifferences_isarchitecturedifferent` string COMMENT 'from deserializer', 
  `currentperformancerisk` string COMMENT 'from deserializer', 
  `recommendationoptions_1_savingsopportunitypercentage` string COMMENT 'from deserializer', 
  `recommendationoptions_1_estimatedmonthlysavings_currency` string COMMENT 'from deserializer', 
  `recommendationoptions_1_estimatedmonthlysavings_value` string COMMENT 'from deserializer', 
  `recommendationoptions_2_savingsopportunitypercentage` string COMMENT 'from deserializer', 
  `recommendationoptions_2_estimatedmonthlysavings_currency` string COMMENT 'from deserializer', 
  `recommendationoptions_2_estimatedmonthlysavings_value` string COMMENT 'from deserializer', 
  `recommendationoptions_3_savingsopportunitypercentage` string COMMENT 'from deserializer', 
  `recommendationoptions_3_estimatedmonthlysavings_currency` string COMMENT 'from deserializer', 
  `recommendationoptions_3_estimatedmonthlysavings_value` string COMMENT 'from deserializer', 
  `effectiverecommendationpreferencesinferredworkloadtypes` string COMMENT 'from deserializer', 
  `inferredworkloadtypes` string COMMENT 'from deserializer', 
  `recommendationoptions_1_migrationeffort` string COMMENT 'from deserializer', 
  `recommendationoptions_2_migrationeffort` string COMMENT 'from deserializer', 
  `recommendationoptions_3_migrationeffort` string COMMENT 'from deserializer', 
  `effectiverecommendationpreferencescpuvendorarchitectures` string COMMENT 'from deserializer', 
  `effectiverecommendationpreferencesenhancedinfrastructuremetrics` string COMMENT 'from deserializer', 
  `effectiverecommendationpreferencesexternalmetricssource` string COMMENT 'from deserializer', 
  `instancestate` string COMMENT 'from deserializer', 
  `tags` string COMMENT 'from deserializer')
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
WITH SERDEPROPERTIES ( 
  'quoteChar'='\"', 
  'separatorChar'=',') 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  's3://data-bucket/compute_optimizer/compute_optimizer_ec2_instance'
TBLPROPERTIES (
  'skip.header.line.count'='1')