# Copyright © Amazon.com and Affiliates: This deliverable is considered Developed Content as defined in the AWS Service Terms and the SOW between the parties dated 2022.

AWSTemplateFormatVersion: 2010-09-09
Description: Deployment of CID dashboard prerequisites

Parameters:
  CidBucket:
    Description: A pre-exist bucket without path where the Athena query results will go to
    Type: String
    Default: aws-athena-query-results-111111111111-gov-west-1
  DataBucket:
    Description: A pre-exist bucket without path where the data resides
    Type: String
    Default: cid-cur-111111111111-gov-west-1
  QuickSightDataSourceRoleName:
    Type: String
    Default: CidQuickSightDataSourceRole
    Description: IAM Role Name to be used on QuickSight Datasource Creation
  AthenaWorkgroup:
    Type: String
    Default: CID
  DatabaseName:
    Type: String
    Description: The Glue/Athena database name
    Default: cid
  RolePath:
    Description: Path for roles where PermissionBoundaries can limit location
    Type: String
    Default: project/
  Prefix:
    Description: The prefix for Lambda function names and IAM resources
    Type: String
    Default: project
  CrawlerName:
    Type: String
    Description: Name of the Glue crawler
    Default: project-quicksight-cid-crawler
  TablePrefix:
    Type: String
    Description: Prefix for the table names created by the crawler
    Default: cur
  CrawlerSchedule:
    Type: String
    Description: Cron expression for crawler schedule (leave empty for on-demand)
    Default: cron(0 0 * * ? *)

Resources:

  CidDatabase:
    Type: AWS::Glue::Database
    Properties:
      DatabaseInput:
        Name: !Ref DatabaseName
      CatalogId: !Sub ${AWS::AccountId}

  MyAthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: !Ref AthenaWorkgroup
      Description: Used for CloudIntelligenceDashboards
      WorkGroupConfiguration:
        EnforceWorkGroupConfiguration: true
        ResultConfiguration:
          EncryptionConfiguration:
            EncryptionOption: SSE_S3
          OutputLocation: !Sub s3://${CidBucket}/

  QuickSightDataSourceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - quicksight.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: !Sub /${RolePath}
      RoleName: !Sub ${Prefix}-${QuickSightDataSourceRoleName}
      # PermissionsBoundary: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/path/permission-boundary
      Policies:
        - PolicyName: AthenaAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AllowAthenaReads
                Effect: Allow
                Action:
                  - athena:ListDataCatalogs
                  - athena:ListDatabases
                  - athena:ListTableMetadata
                Resource: '*'
                
              - Sid: AllowAthena
                Effect: Allow
                Action:
                  - athena:GetQueryExecution
                  - athena:GetQueryResults
                  - athena:StartQueryExecution
                  - athena:GetQueryResultsStream
                  - athena:GetTableMetadata
                Resource:
                  - !Sub arn:${AWS::Partition}:glue:${AWS::Region}:${AWS::AccountId}:database/${DatabaseName}
                  - !Sub arn:${AWS::Partition}:athena:${AWS::Region}:${AWS::AccountId}:workgroup/${MyAthenaWorkGroup}

              - Sid: AllowS3
                Effect: Allow
                Action:
                  - s3:GetBucketLocation
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:ListBucketMultipartUploads
                  - s3:ListMultipartUploadParts
                  - s3:AbortMultipartUpload
                Resource:
                  - !Sub arn:${AWS::Partition}:s3:::${CidBucket}
                  - !Sub arn:${AWS::Partition}:s3:::${CidBucket}/*

              - Sid: AllowCUR
                Effect: Allow
                Action:
                  - s3:GetBucketLocation
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:ListBucketMultipartUploads
                  - s3:ListMultipartUploadParts
                Resource:
                  - !Sub arn:${AWS::Partition}:s3:::${DataBucket}
                  - !Sub arn:${AWS::Partition}:s3:::${DataBucket}/*

              - Sid: AllowGlue
                Effect: Allow
                Action:
                  - glue:GetPartition
                  - glue:GetPartitions
                  - glue:GetDatabase
                  - glue:GetDatabases
                  - glue:GetTable
                  - glue:GetTables
                Resource:
                  - !Sub arn:${AWS::Partition}:glue:${AWS::Region}:${AWS::AccountId}:catalog
                  - !Sub arn:${AWS::Partition}:glue:${AWS::Region}:${AWS::AccountId}:database/${DatabaseName}
                  - !Sub arn:${AWS::Partition}:glue:${AWS::Region}:${AWS::AccountId}:table/${DatabaseName}/*

  GlueCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      Path: !Sub /${RolePath}
      RoleName: !Sub ${Prefix}-${CrawlerName}
      # PermissionsBoundary: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/path/permission-boundary
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: S3BucketAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:${AWS::Partition}:s3:::\${DataBucket}*
                  - !Sub arn:${AWS::Partition}:s3:::\${DataBucket}

  GlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Ref CrawlerName
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref DatabaseName
      TablePrefix: !Ref TablePrefix
      Schedule:
        ScheduleExpression: !Ref CrawlerSchedule
      Targets:
        S3Targets:
          - Path: !Ref DataBucket
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      Configuration: '{"Version":1.0,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"},"Tables":{"AddOrUpdateBehavior":"MergeNewColumns"}}}'

Outputs:
  QuickSightDataSourceRoleArn:
    Description: Dashboard data source arn
    Value: !GetAtt QuickSightDataSourceRole.Arn

  CrawlerRoleARN:
    Description: ARN of the IAM role created for the Glue crawler
    Value: !GetAtt GlueCrawlerRole.Arn

  CrawlerName:
    Description: Name of the created Glue crawler
    Value: !Ref GlueCrawler