AWSTemplateFormatVersion: '2010-09-09'
Description: A Plugin for Cloud Intelligence Dashboards v0.0.1

Parameters:
  DashboardId:
    Type: String
    Description:  'Dashboard id'
    Default: ''
    AllowedPattern: "^[a-zA-Z0-9_-]*$"
  ResourcesUrl:
    Type: String
    Description:  'Resources File URL. Keep it empty if not sure.'
    Default: ''
  RequiresDataCollection:
    Type: String
    Description:  'Is DataCollectionRequired'
    AllowedValues: ["yes", "no"]
    Default: 'no'
  RequiresDataExports:
    Type: String
    Description:  'Is DataCollectionRequired'
    AllowedValues: ["yes", "no"]
    Default: 'no'
  RequiresAccountMapDatabase:
    Type: String
    Description:  'Is AccountMapDatabaseRequired'
    AllowedValues: ["yes", "no"]
    Default: 'no'

Conditions:
  ResourcesUrlIsEmpty: !Equals [!Ref ResourcesUrl, '']
  RequiresDataCollection: !Equals [!Ref RequiresDataCollection, 'yes']
  RequiresDataExports: !Equals [!Ref RequiresDataExports, 'yes']
  RequiresAccountMapDatabase: !Equals [!Ref RequiresAccountMapDatabase, 'yes']

Resources:
  Dashboard:
    Type: Custom::CidDashboard
    Properties:
      Name: !Ref DashboardId
      ServiceToken: {'Fn::ImportValue': "cid-CidExecArn"}
      Dashboard:
        dashboard-id: !Ref DashboardId
        account-map-source: 'dummy'
        account-map-database-name: !If [RequiresAccountMapDatabase, {'Fn::ImportValue':  "cid-CidDatabase"}, !Ref 'AWS::NoValue']
        data-collection-database-name: 'optimization_data'
        resources: !If [ResourcesUrlIsEmpty, !Ref 'AWS::NoValue', !Ref ResourcesUrl]
        data_exports_database_name: !If [RequiresDataExports, {'Fn::ImportValue':  "cid-DataExports-Database"}, !Ref 'AWS::NoValue']
        data_collection_database_name: !If [RequiresDataCollection, {'Fn::ImportValue':  "cid-DataCollection-Database"}, !Ref 'AWS::NoValue']

Outputs:
  DashboardURL:
    Description: "URL of Dashboard"
    Value: !GetAtt Dashboard.DashboardURL
