CREATE EXTERNAL TABLE IF NOT EXISTS cur2 (
  bill_bill_type STRING,
  bill_billing_entity STRING,
  bill_billing_period_end_date TIMESTAMP,
  bill_billing_period_start_date TIMESTAMP,
  bill_invoice_id STRING,
  bill_invoicing_entity STRING,
  bill_payer_account_id STRING,
  bill_payer_account_name STRING,
  cost_category MAP<STRING, STRING>,
  discount MAP<STRING, DOUBLE>,
  discount_bundled_discount DOUBLE,
  discount_total_discount DOUBLE,
  identity_line_item_id STRING,
  identity_time_interval STRING,
  line_item_usage_account_name STRING,
  line_item_availability_zone STRING,
  line_item_blended_cost DOUBLE,
  line_item_blended_rate DOUBLE,
  line_item_currency_code STRING,
  line_item_legal_entity STRING,
  line_item_line_item_description STRING,
  line_item_line_item_type STRING,
  line_item_net_unblended_cost DOUBLE,
  line_item_net_unblended_rate DOUBLE,
  line_item_normalization_factor DOUBLE,
  line_item_normalized_usage_amount DOUBLE,
  line_item_operation STRING,
  line_item_product_code STRING,
  line_item_resource_id STRING,
  line_item_tax_type STRING,
  line_item_unblended_cost DOUBLE,
  line_item_unblended_rate DOUBLE,
  line_item_usage_account_id STRING,
  line_item_usage_amount DOUBLE,
  line_item_usage_end_date TIMESTAMP,
  line_item_usage_start_date TIMESTAMP,
  line_item_usage_type STRING,
  pricing_currency STRING,
  pricing_lease_contract_length STRING,
  pricing_offering_class STRING,
  pricing_public_on_demand_cost DOUBLE,
  pricing_public_on_demand_rate DOUBLE,
  pricing_purchase_option STRING,
  pricing_rate_code STRING,
  pricing_rate_id STRING,
  pricing_term STRING,
  pricing_unit STRING,
  product MAP<STRING, STRING>,
  product_comment STRING,
  product_fee_code STRING,
  product_fee_description STRING,
  product_from_location STRING,
  product_from_location_type STRING,
  product_from_region_code STRING,
  product_instanceSKU STRING,
  product_instance_family STRING,
  product_instance_type STRING,
  product_location STRING,
  product_location_type STRING,
  product_operation STRING,
  product_pricing_unit STRING,
  product_product_family STRING,
  product_region_code STRING,
  product_sku STRING,
  product_service_code STRING,
  product_to_location_type STRING,
  product_to_location STRING,
  product_to_region_code STRING,
  product_usagetype STRING,
  reservation_amortized_upfront_cost_for_usage DOUBLE,
  reservation_amortized_upfront_fee_for_billing_period DOUBLE,
  reservation_availability_zone STRING,
  reservation_effective_cost DOUBLE,
  reservation_end_time STRING,
  reservation_modification_status STRING,
  reservation_net_amortized_upfront_cost_for_usage DOUBLE,
  reservation_net_amortized_upfront_fee_for_billing_period DOUBLE,
  reservation_net_effective_cost DOUBLE,
  reservation_net_recurring_fee_for_usage DOUBLE,
  reservation_net_unused_amortized_upfront_fee_for_billing_period DOUBLE,
  reservation_net_unused_recurring_fee DOUBLE,
  reservation_net_upfront_value DOUBLE,
  reservation_normalized_units_per_reservation STRING,
  reservation_number_of_reservations STRING,
  reservation_recurring_fee_for_usage DOUBLE,
  reservation_reservation_a_r_n STRING,
  reservation_start_time STRING,
  reservation_subscription_id STRING,
  reservation_total_reserved_normalized_units STRING,
  reservation_total_reserved_units STRING,
  reservation_units_per_reservation STRING,
  reservation_unused_amortized_upfront_fee_for_billing_period DOUBLE,
  reservation_unused_normalized_unit_quantity DOUBLE,
  reservation_unused_quantity DOUBLE,
  reservation_unused_recurring_fee DOUBLE,
  reservation_upfront_value DOUBLE,
  resource_tags MAP<STRING, STRING>,
  savings_plan_amortized_upfront_commitment_for_billing_period DOUBLE,
  savings_plan_end_time STRING,
  savings_plan_instance_type_family STRING,
  savings_plan_net_amortized_upfront_commitment_for_billing_period DOUBLE,
  savings_plan_net_recurring_commitment_for_billing_period DOUBLE,
  savings_plan_net_savings_plan_effective_cost DOUBLE,
  savings_plan_offering_type STRING,
  savings_plan_payment_option STRING,
  savings_plan_purchase_term STRING,
  savings_plan_recurring_commitment_for_billing_period DOUBLE,
  savings_plan_region STRING,
  savings_plan_savings_plan_a_r_n STRING,
  savings_plan_savings_plan_effective_cost DOUBLE,
  savings_plan_savings_plan_rate DOUBLE,
  savings_plan_start_time STRING,
  savings_plan_total_commitment_to_date DOUBLE,
  savings_plan_used_commitment DOUBLE,
  split_line_item_actual_usage DOUBLE,
  split_line_item_net_split_cost DOUBLE,
  split_line_item_net_unused_cost DOUBLE,
  split_line_item_parent_resource_id STRING,
  split_line_item_public_on_demand_split_cost DOUBLE,
  split_line_item_public_on_demand_unused_cost DOUBLE,
  split_line_item_reserved_usage DOUBLE,
  split_line_item_split_cost DOUBLE,
  split_line_item_split_usage DOUBLE,
  split_line_item_split_usage_ratio DOUBLE,
  split_line_item_unused_cost DOUBLE
)
PARTITIONED BY (`BILLING_PERIOD` string,
    `partition_1` string)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://bucket/cur2/export/path/data/'
TBLPROPERTIES (
  'classification'='parquet', 
  'compressionType'='none', 
  'partition_filtering.enabled'='true', 
  'typeOfData'='file')